[package]
name = "gakusyun-doc"
version = "2.0.0"
entrypoint = "src/lib.typ"
authors = ["Gakusyun <gxj@gxj62.cn>"]
license = "MIT"
description = "一个专注于中文的Typst文档模板，提供高度自定义的排版样式。"
repository = "https://github.com/gakusyun/gakusyun-doc"
keywords = ["chinese", "document", "template", "bilingual"]
categories = ["report", "paper", "book"]
disciplines = ["education", "computer-science"]
compiler = "0.14.0"

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"